server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate     /etc/ssl/certs/crt.pem;
    ssl_certificate_key /etc/ssl/certs/key.pem;

    server_name lf4a.com www.lf4a.com;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://api.lf4a.com:5000/;

        proxy_ssl_server_name on;
        proxy_ssl_name api.lf4a;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca.pem;
    }

    location /auth/ {
        proxy_pass https://auth.lf4a.com:8443;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_ssl_server_name on;
        proxy_ssl_name auth.lf4a.com;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca.pem;
    }

    location /storage/ {
        proxy_pass https://minio.lf4a.com:9000/;
        
        proxy_set_header Host minio.lf4a.com:9000;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_ssl_server_name on;
        proxy_ssl_name minio.lf4a.com;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca.pem;
    }
}
