server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate     /etc/ssl/certs/crt.pem;
    ssl_certificate_key /etc/ssl/certs/key.pem;

    server_name lf4a.com;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass https://api.lf4a.com:5000;
        proxy_ssl_server_name on;
        proxy_ssl_name api.lf4a;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca.pem;
    }
}
