services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    depends_on:
      - go-api
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./secrets/ca.pem:/etc/ssl/certs/ca.pem
      - ./secrets/web.crt:/etc/ssl/certs/crt.pem
      - ./secrets/web.key:/etc/ssl/certs/key.pem
    networks:
      - backend
      - keycloak
      - minio

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    restart: always
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/tls.key
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_PROXY_HEADERS: "xforwarded"
    command: start --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ./secrets/ca.pem:/opt/keycloak/conf/certs/ca.pem
      - ./secrets/keycloak.crt:/opt/keycloak/conf/certs/tls.crt
      - ./secrets/keycloak.key:/opt/keycloak/conf/certs/tls.key
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      keycloak:
        aliases:
          - auth.lf4a.com
      backend:
  
  postgres:
    image: postgres:16
    container_name: keycloak_db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Go API Service
  go-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    restart: always
    container_name: go-api
    image: lf4a/mqtt-ss-api:local
    env_file: ./server/.env
    depends_on:
      mongo-db:
        condition: service_started
      broker:
        condition: service_started
      keycloak:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - api.lf4a.com
      db:
      minio:
      broker:
      keycloak:
    volumes:
      - ./secrets/ca.pem:/certs/ca.crt
      - ./secrets/server.crt:/certs/server.crt
      - ./secrets/server.key:/certs/server.key
      - ./secrets/client.crt:/certs/client.crt
      - ./secrets/client.key:/certs/client.key

  broker:
    user: "${UID}:${GID}"
    image: eclipse-mosquitto:latest
    restart: always
    container_name: broker
    hostname: broker
    ports:
      - 8883:8883
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./secrets/ca.pem:/certs/ca.crt
      - ./secrets/broker.crt:/certs/server.crt
      - ./secrets/broker.key:/certs/server.key
    networks:
      - broker

  mongo-db:
    container_name: mongo-db
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    command: ["--auth"]
    volumes:
      - mongo-data:/data/db
    networks:
      - db
  
  mongo-express:
    container_name: mongo-express
    restart: always
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-password}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_SERVER: "mongo-db"
      ME_CONFIG_SITE_SSL_ENABLED: "true"
      ME_CONFIG_SITE_SSL_CRT_PATH: "/certs/express.crt"
      ME_CONFIG_SITE_SSL_KEY_PATH: "/certs/express.key"
    ports:
      - 8082:8081
    depends_on:
      - mongo-db
    networks:
      - db
    volumes:
      - ./secrets/express.crt:/certs/express.crt
      - ./secrets/express.key:/certs/express.key
  
  minio:
    container_name: minio
    restart: always
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --certs-dir /certs --console-address ":9001"
    ports:
      - 9001:9001
    volumes:
      - minio-data:/data
      - ./secrets/ca.pem:/certs/ca.crt
      - ./secrets/minio.crt:/certs/public.crt
      - ./secrets/minio.key:/certs/private.key
    networks:
      minio:
        aliases:
          - minio.lf4a.com

volumes:
  mongo-data:
  minio-data:
  postgres-data:

networks:
  keycloak:
  backend:
  db:
  minio:
  broker:
