listener 8883
protocol mqtt

cafile   /certs/ca.crt
certfile /certs/server.crt
keyfile  /certs/server.key

tls_version tlsv1.2
ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305

require_certificate true
use_identity_as_username true
allow_anonymous false


acl_file /mosquitto/config/acl.conf

max_connections 100
max_inflight_messages 20
max_queued_messages 100


persistence true
persistence_location /mosquitto/data/

log_type error
log_type warning
log_type notice
log_type information
log_type subscribe
log_type unsubscribe
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
connection_messages true
